spring.application.name=flexit-backend
spring.data.mongodb.uri=mongodb+srv://chathumi:chathu2025@tastetogether.fzrix4v.mongodb.net/AuraGemDB?retryWrites=true&w=majority&appName=TasteTogether
server.port=8080
